/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanagementnahom;

import java.awt.event.*;
import java.util.EventObject;
import javax.swing.event.*;
import javax.swing.table.*;
import javax.swing.*;
import java.io.File;
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    static String selectedId;
    public Main() {
        initComponents();
        updateAll();
        tblCustomers.getSelectionModel().addListSelectionListener(
         new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
            int row=tblCustomers.getSelectedRow();
        
        if(row!=-1){
            Object value=tblCustomers.getValueAt(row,10);
            System.out.println("VAlue: "+value);
            selectedId=(String)value;
            if(selectedId!=null){
            String username=Person.findPersonById(selectedId).getUsername();
            String url=DB.getResult("user","imagePath","username='"+username+"'");
            Icon icon=null;
            if(!url.contains("profile"))
                icon=new ImageIcon(url);
            else
            icon = new ImageIcon(this.getClass().getResource(url));
            lblImage.setIcon(icon);
            }
            else
                lblImage.setIcon(null);
        }    
            }
             
         }
        );
        
      
    }
    public void refresh(){
        Main main=new Main();
        main.setSize(main.getPreferredSize());
        main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        main.setVisible(true);
        this.dispose();
        
    }
    public void updateAll(){
    String[] ids=Customer.getIds();
    cboId.removeAllItems();
    cboFromCustomer.removeAllItems();
    cboToCustomer.removeAllItems();
    cboUsername.removeAllItems();
    String[] accounts=DB.getColumn("account","accountnumber");
    for(String s:accounts){
        if(s!=null){
            cboFromCustomer.addItem(s);
            cboToCustomer.addItem(s);
        }
    }
    String[] users=DB.getColumn("customer","username");
    for(String u:users){
        if(u!=null){
            cboUsername.addItem(u);
        }
    }
    String[] fn=DB.getColumn("customer", "firstname");
    String[] ln=DB.getColumn("customer","lastname");
    //String[] names=new String[fn.length];
    cboCustomer.removeAllItems();
    for(int i=0; i<fn.length;i++){
        //names[i]=fn[i]+ln[i];
        if(fn[i]!=null){
            cboCustomer.addItem(fn[i]+" "+ln[i]);
        }
    }
    for(String i:ids){
        if(i!=null)
            cboId.addItem(i);
    }
    txtLog.setText(Logger.getLog());
    }
    public void dataUpdate(int row,int col){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        btnDeleteCustomer = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cboId = new javax.swing.JComboBox<>();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        cboAge = new javax.swing.JSpinner();
        cboSex = new javax.swing.JComboBox<>();
        txtUsername1 = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        cboPhone = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        cboCity = new javax.swing.JComboBox<>();
        cboCountry = new javax.swing.JComboBox<>();
        txtAccountNo = new javax.swing.JTextField();
        txtPassword2 = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboFromCustomer = new javax.swing.JComboBox<>();
        cboToCustomer = new javax.swing.JComboBox<>();
        txtAmount1 = new javax.swing.JTextField();
        btnTransfer = new javax.swing.JButton();
        lblAmount = new javax.swing.JLabel();
        lblAmount2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboCustomer = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtAmount2 = new javax.swing.JTextField();
        btnDeposite = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tbtBalance = new javax.swing.JToggleButton();
        tbtDeposite = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtRepeatPassword = new javax.swing.JPasswordField();
        btnImageSelect = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblImageLabel = new javax.swing.JLabel();
        cboUsername = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton6.setText("Customer Management");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(454, 167, 204, 39);

        jButton7.setText("Transaction");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(454, 217, 204, 44);

        jButton8.setText("Settings");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(454, 272, 204, 43);

        jButton9.setText("Log (History)");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(454, 326, 204, 41);

        jButton10.setText("Exit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(454, 378, 204, 36);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanagementnahom/bank1.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 740, 430);

        tabPane.addTab("Home", jPanel1);

        jPanel2.setLayout(null);

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            Customer.getTable(),
            new String [] {
                "firstname", "lastname", "age", "sex","phone","email","city","country","account","Username","id","Balance"
            }
        ));
        tblCustomers.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblCustomersFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomers);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 729, 216);

        btnDeleteCustomer.setText("Delete");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeleteCustomer);
        btnDeleteCustomer.setBounds(552, 402, 70, 23);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(btnRefresh);
        btnRefresh.setBounds(633, 402, 71, 23);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("ID:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(50, 230, 50, 14);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Firstname:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 262, 80, 15);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Lastname:");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 290, 80, 15);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Age:");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(40, 330, 40, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Phone:");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(260, 230, 70, 15);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Email:");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(260, 260, 60, 15);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("City:");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(270, 290, 60, 15);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Country:");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(250, 320, 80, 15);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Sex:");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(40, 360, 60, 15);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Account No:");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(230, 350, 90, 15);

        lblImage.setText("Image");
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });
        jPanel2.add(lblImage);
        lblImage.setBounds(561, 227, 168, 140);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Username:");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(0, 390, 90, 15);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Password:");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(240, 390, 90, 15);

        cboId.setEditable(true);
        cboId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIdActionPerformed(evt);
            }
        });
        jPanel2.add(cboId);
        cboId.setBounds(100, 230, 130, 20);
        jPanel2.add(txtFirstname);
        txtFirstname.setBounds(100, 260, 130, 20);
        jPanel2.add(txtLastname);
        txtLastname.setBounds(100, 290, 130, 20);
        jPanel2.add(cboAge);
        cboAge.setBounds(100, 330, 40, 20);

        cboSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        jPanel2.add(cboSex);
        cboSex.setBounds(100, 360, 120, 20);
        jPanel2.add(txtUsername1);
        txtUsername1.setBounds(100, 390, 120, 20);
        jPanel2.add(txtPhone);
        txtPhone.setBounds(420, 230, 100, 20);

        cboPhone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+251", "+252", "+253" }));
        jPanel2.add(cboPhone);
        cboPhone.setBounds(340, 230, 70, 20);
        jPanel2.add(txtEmail);
        txtEmail.setBounds(340, 260, 160, 20);

        cboCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arbaminch", "Addis Ababa", "Hawasa", "Bahir Dar", "Mekele", "Jimma" }));
        jPanel2.add(cboCity);
        cboCity.setBounds(340, 290, 160, 20);

        cboCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ethiopia", "Kenya" }));
        jPanel2.add(cboCountry);
        cboCountry.setBounds(340, 320, 160, 20);
        jPanel2.add(txtAccountNo);
        txtAccountNo.setBounds(340, 350, 160, 20);
        jPanel2.add(txtPassword2);
        txtPassword2.setBounds(340, 390, 160, 20);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubmit);
        btnSubmit.setBounds(550, 370, 65, 23);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);
        btnUpdate.setBounds(630, 370, 70, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanagementnahom/bank2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(4, 4, 730, 420);

        tabPane.addTab("Customer Management", jPanel2);

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Account Balance Transfer service");

        jLabel2.setText("From:");

        jLabel3.setText("To:");

        jLabel4.setText("Amount:");

        cboFromCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFromCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFromCustomerActionPerformed(evt);
            }
        });

        cboToCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboToCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboToCustomerActionPerformed(evt);
            }
        });

        txtAmount1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAmount1FocusLost(evt);
            }
        });
        txtAmount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmount1ActionPerformed(evt);
            }
        });

        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        lblAmount.setText("0.00");

        lblAmount2.setText("0.00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(cboFromCustomer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboToCustomer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAmount1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboFromCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboToCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnTransfer)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(153, 255, 153));
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Deposite or Withdraw from Customer Account");

        jLabel10.setText("Customer Name:");

        cboCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCustomerActionPerformed(evt);
            }
        });

        jLabel11.setText("Amount:");

        btnDeposite.setText("Deposite");
        btnDeposite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositeActionPerformed(evt);
            }
        });

        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        jLabel14.setText("Account:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(btnDeposite, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(45, 45, 45)
                                            .addComponent(txtAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeposite)
                    .addComponent(btnWithdraw))
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Bank Transaction Management");

        tbtBalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbtBalance.setText("Balance Transfer");
        tbtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtBalanceActionPerformed(evt);
            }
        });

        tbtDeposite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbtDeposite.setText("Deposite or Withdraw");
        tbtDeposite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtDepositeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tbtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(tbtDeposite, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbtBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(tbtDeposite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tabPane.addTab("Transaction", jPanel3);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Change Customer Login details");

        jLabel16.setText("Username:");

        jLabel17.setText("Existing Password:");

        txtPassword.setText("jPasswordField1");

        txtRepeatPassword.setText("jPasswordField2");

        btnImageSelect.setText("Browse");
        btnImageSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageSelectActionPerformed(evt);
            }
        });

        jLabel18.setText("New Password:");

        jLabel19.setText("Profile Image:");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblImageLabel.setText("your profile image goes here");

        cboUsername.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnImageSelect)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtRepeatPassword)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboUsername, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(lblImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(cboUsername))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRepeatPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImageSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        tabPane.addTab("Settings", jPanel4);

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane2.setViewportView(txtLog);

        btnSave.setText("Save");

        btnDelete.setText("Delete");

        btnClear.setText("Clear");

        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 158, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tabPane.addTab("Log (history)", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.tabPane.setSelectedIndex(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.tabPane.setSelectedIndex(2);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.tabPane.setSelectedIndex(3);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.tabPane.setSelectedIndex(4);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tblCustomersFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblCustomersFocusGained
        
    }//GEN-LAST:event_tblCustomersFocusGained

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
      JFileChooser chooser=new JFileChooser();
      int result=chooser.showOpenDialog(this);
      File f=chooser.getSelectedFile();
      if(result==JFileChooser.APPROVE_OPTION && f!=null){
        try{
            
        
         Process p=Runtime.getRuntime().exec("cmd /c copy "+f.getAbsolutePath()+" "+"C:\\Users\\Nahom\\Documents\\NetBeansProjects\\BankManagementNahom\\src\\bankmanagementnahom\\profile");
         Thread.sleep(2000);
         System.out.println("File: "+f.getName());
         Icon icon=new ImageIcon("C:\\Users\\Nahom\\Documents\\NetBeansProjects\\BankManagementNahom\\src\\bankmanagementnahom\\profile\\"+f.getName());
         lblImage.setIcon(icon);
         String path="profile/"+f.getName();
         Person person=Person.findPersonById(selectedId);
         if(person!=null){
         String user=person.getUsername();
         User u=User.findUser(user);
         u.setImagePath(path);
         }
         else 
             selectedImage=f.getAbsolutePath();
        }catch(Exception e){
            e.printStackTrace();
        }
      }
    }//GEN-LAST:event_lblImageMouseClicked
    static String selectedImage;
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String id=(String)cboId.getSelectedItem();
        String firstname=txtFirstname.getText();
        String lastname=txtLastname.getText();
        String sex=(String)cboSex.getSelectedItem();
        int age=(int)cboAge.getModel().getValue();
        String username=txtUsername1.getText();
        String phone=(String)cboPhone.getSelectedItem()+txtPhone.getText();
        String email=txtEmail.getText();
        String city=(String)cboCity.getSelectedItem();
        String country=(String)cboCountry.getSelectedItem();
        String password=String.valueOf(txtPassword2.getPassword());
        String account=txtAccountNo.getText();
        boolean a=Customer.addCustomer(firstname, lastname, age, sex, phone, email, city, country, account, username, id);
        boolean b=User.addUser(username, password,User.Types.customer,selectedImage);
        boolean c=DB.executeUpdate("insert into account values('"+id+"','"+account+"','0')");
        if(!a)
            JOptionPane.showMessageDialog(null,"Unable to add customer");
        if(!b)
            JOptionPane.showMessageDialog(null,"Unable to add new user");
        if(!c) 
            JOptionPane.showMessageDialog(null,"Unable to create new account");
                    
        if(a&&b&&c){
            
            JOptionPane.showMessageDialog(this,"Customer Added Succesfully");
            Logger.addLog("Customer Added: Name: "+firstname+" "+lastname);
            refresh();
            
        }
        else JOptionPane.showMessageDialog(this, "Error: Invalid parameters, please check");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cboIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIdActionPerformed
        String id=(String)cboId.getSelectedItem();
        Person p=Person.findPersonById(id);
        if(p==null)
            return;
        txtFirstname.setText(p.getFirstName());
        txtLastname.setText(p.getLastName());
        cboAge.setValue(p.getAge());
        cboSex.setSelectedItem(p.getSex());
        txtPhone.setText(p.getPhone());
        txtUsername1.setText(p.getUsername());
        txtEmail.setText(p.getEmail());
        cboCity.setSelectedItem(p.getCity());
        cboCountry.setSelectedItem(p.getCountry());
        Account a=Account.findAccount(id);
        txtAccountNo.setText(a.getAccountNumber());
        txtPassword2.setText(User.findUser(p.getUsername()).getPassword());
    }//GEN-LAST:event_cboIdActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       String id=(String)cboId.getSelectedItem();
        String firstname=txtFirstname.getText();
        String lastname=txtLastname.getText();
        String sex=(String)cboSex.getSelectedItem();
        int age=(int)cboAge.getModel().getValue();
        String username=txtUsername1.getText();
        String phone=(String)cboPhone.getSelectedItem()+txtPhone.getText();
        String email=txtEmail.getText();
        String city=(String)cboCity.getSelectedItem();
        String country=(String)cboCountry.getSelectedItem();
        String password=String.valueOf(txtPassword2.getPassword());
        String account=txtAccountNo.getText();
        if(Customer.setFirstName(id,firstname) &&
           Customer.setLastName(id, lastname) &&
           Customer.setAge(id,age) &&
           Customer.setSex(id, sex) &&
           Customer.setCity(id, city) &&
           Customer.setCountry(id, country) &&
           Customer.setEmail(id, email) &&
           Customer.setPhone(id, phone) &&
           Customer.setUsername(id, username) &&
           Customer.setAccount(id, account)){
         JOptionPane.showMessageDialog(Main.this,"Succesfully updated customer data for: "+firstname+" "+lastname+"","Success",JOptionPane.INFORMATION_MESSAGE);
         Logger.addLog("Customer updated: "+firstname+" "+lastname);
         refresh();
        }
        else 
            JOptionPane.showMessageDialog(this,"Error: Update failed","Error",JOptionPane.ERROR_MESSAGE);
           
           
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed
        String id=(String)cboId.getSelectedItem();
        String query="delete from customer where id='"+id+"'";
        if(DB.executeUpdate(query)){
         JOptionPane.showMessageDialog(this,"Customer: "+id+" deleted","Success",JOptionPane.INFORMATION_MESSAGE);
         Logger.addLog("Customer Deleted: "+id);
         refresh();
        }
        else 
            JOptionPane.showMessageDialog(this,"Error: failed to delete customer","Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tbtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtBalanceActionPerformed
        jPanel6.setVisible(tbtBalance.isSelected());
    }//GEN-LAST:event_tbtBalanceActionPerformed

    private void tbtDepositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtDepositeActionPerformed
        jPanel7.setVisible(tbtDeposite.isSelected());
    }//GEN-LAST:event_tbtDepositeActionPerformed

    private void cboFromCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFromCustomerActionPerformed
        String account=(String)cboFromCustomer.getSelectedItem();
        double amount=Account.getBalance(account);
        lblAmount.setText(String.valueOf(amount));
        maxAmount=amount;
    }//GEN-LAST:event_cboFromCustomerActionPerformed
    static double maxAmount=0;
    private void cboToCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboToCustomerActionPerformed
        String account=(String)cboToCustomer.getSelectedItem();
        double amount=Account.getBalance(account);
        lblAmount2.setText(String.valueOf(amount));
    }//GEN-LAST:event_cboToCustomerActionPerformed

    private void txtAmount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmount1ActionPerformed
        
    }//GEN-LAST:event_txtAmount1ActionPerformed

    private void txtAmount1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmount1FocusLost
        String input=txtAmount1.getText();
        if(input==null){
            JOptionPane.showMessageDialog(this,"Please specify a valid amount!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
        double amount=Double.parseDouble(input);
        if(amount>maxAmount){
            JOptionPane.showMessageDialog(this,"Not enough balance to transfer!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Amount should be in Number format!","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtAmount1FocusLost

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        String account=(String)cboFromCustomer.getSelectedItem();
        double balance=Account.getBalance(account);
        String input=txtAmount1.getText();
        double amount=Double.parseDouble(input);
        if(balance<amount){
          JOptionPane.showMessageDialog(this,"Not enough balance to transfer!","Warning",JOptionPane.WARNING_MESSAGE);
          return;
        }
        String account2=(String)cboToCustomer.getSelectedItem();
        if(account.equalsIgnoreCase(account2)){
            JOptionPane.showMessageDialog(this, "Please select a different Account!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean commit1=Account.withdraw(account, amount);
        
        boolean commit2=Account.deposite(account2, amount);
        
        if(commit1 && commit2){
            JOptionPane.showMessageDialog(this,"Transfer Completed succesfully","Success",JOptionPane.INFORMATION_MESSAGE);
            Logger.addLog("Transfer from: "+account+" to "+account2+" Amount: "+amount+"");
        }
        else 
            JOptionPane.showMessageDialog(this, "Tranfer failed!","Error",JOptionPane.ERROR_MESSAGE);
        refresh();
    }//GEN-LAST:event_btnTransferActionPerformed

    private void cboCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCustomerActionPerformed
        String name=(String)cboCustomer.getSelectedItem();
        if(name==null)
            return;
        String[] names=name.split(" ");
        String fn=names[0];
        String ln=names[1];
        Person p=Person.findPersonByName(fn, ln);
        String id=DB.getResult("customer", "id", "username='"+p.getUsername()+"'");
        String account=DB.getResult("account", "accountnumber","id='"+id+"'");
        txtAccount.setText(account);
        txtAmount2.setText(String.valueOf(Account.getBalance(account)));
    }//GEN-LAST:event_cboCustomerActionPerformed

    private void btnDepositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositeActionPerformed
        String account=txtAccount.getText();
        double amount=Double.parseDouble(txtAmount2.getText());
        
        if(Account.deposite(account, amount)){
            JOptionPane.showMessageDialog(this,"Deposited: "+amount+" in account: "+account,"Success",JOptionPane.INFORMATION_MESSAGE);
        Logger.addLog("Deposite: ammount= "+amount+" for account: "+account);
            refresh();
        }
        else JOptionPane.showMessageDialog(this, "Deposite failed!","Error",JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_btnDepositeActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        String account=txtAccount.getText();
        double amount=Double.parseDouble(txtAmount2.getText());
        if(Account.withdraw(account, amount)){
            JOptionPane.showMessageDialog(this,"Withdraw: "+amount+"br from account: "+account,"Success",JOptionPane.INFORMATION_MESSAGE);
            Logger.addLog("Withdraw: amount: "+amount+" br from account: "+account);
         refresh();
        }
        else JOptionPane.showMessageDialog(this, "Error: Not Enought Balance!","Error",JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void cboUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUsernameActionPerformed
        String username=(String)cboUsername.getSelectedItem();
        if(username==null)
            return;
        String url=DB.getResult("user","imagepath","username='"+username+"'");
        if(url!=null)
            lblImageLabel.setIcon(new ImageIcon(url));
        
    }//GEN-LAST:event_cboUsernameActionPerformed

    private void btnImageSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageSelectActionPerformed
        JFileChooser chooser=new JFileChooser();
      int result=chooser.showOpenDialog(this);
      File f=chooser.getSelectedFile();
      if(result==JFileChooser.APPROVE_OPTION && f!=null){
          String path=f.getAbsolutePath();
          filePath=path;
          lblImageLabel.setIcon(new ImageIcon(path));
      }
    }//GEN-LAST:event_btnImageSelectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String image=filePath;
        String username=(String)cboUsername.getSelectedItem();
        String password=User.findUser(username).getPassword();
        String pass1=String.valueOf(txtPassword.getPassword());
        String pass2=String.valueOf(txtRepeatPassword.getPassword());
        if(password.equalsIgnoreCase(pass1)){
           if(DB.update("user", "password", pass2,"username='"+username+"'")&&
            DB.update("user","imagepath",image,"username='"+username+"'")){
               
               Logger.addLog("Account update for: "+username);
               JOptionPane.showMessageDialog(this,"Customer data updated");
           }
           else JOptionPane.showMessageDialog(this,"Customer not updated!");
        }
        else JOptionPane.showMessageDialog(this,"Password is not correct!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        this.txtLog.setText(Logger.getLog());
    }//GEN-LAST:event_btnReloadActionPerformed
    static String filePath;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnDeposite;
    private javax.swing.JButton btnImageSelect;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JSpinner cboAge;
    private javax.swing.JComboBox<String> cboCity;
    private javax.swing.JComboBox<String> cboCountry;
    private javax.swing.JComboBox<String> cboCustomer;
    private javax.swing.JComboBox<String> cboFromCustomer;
    private javax.swing.JComboBox<String> cboId;
    private javax.swing.JComboBox<String> cboPhone;
    private javax.swing.JComboBox<String> cboSex;
    private javax.swing.JComboBox<String> cboToCustomer;
    private javax.swing.JComboBox<String> cboUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblAmount2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImageLabel;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JToggleButton tbtBalance;
    private javax.swing.JToggleButton tbtDeposite;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextField txtAccountNo;
    private javax.swing.JTextField txtAmount1;
    private javax.swing.JTextField txtAmount2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JPasswordField txtRepeatPassword;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
